# Generated by Django 5.0.6 on 2024-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryMap', '0002_markedplaces_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markedplaces',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
